version: "3.2"
services:
  genome-annotations:
    container_name: genome-annotations
    image: dictybase/migration-data-export
    volumes:
        - data:/data
        - config:/config
        - log:/log
    env_file:
        - ./common.env
    command: ["geneannotation"]
volumes:
    data: {}
    config: {}
    log: {}
