version: "3.2"
services:
  literature:
    container_name: literature
    image: dictybase/migration-data-export
    volumes:
        - data:/data
        - config:/config
        - log:/log
    env_file:
        - ./common.env
    command: ["literature"] 
volumes:
    data: {}
    config: {}
    log: {}
